name: Publish NPM

on:
  push:
    branches:
      - release

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Publish to NPM
        run: bun run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}